baseURL = "https://agsanar.github.io/"
languageCode = "en-us"
title = "Agsanar's Tome"
theme = "hello-friend-ng"

[params]
  author = "Agostinho Sanches"
  description = "A little about everything."
  homeSubtitle = "A little about everything."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/agsanar"

[taxonomies]
  tag      = "tags"
  category = "categories"
